name: Build Done.ino

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32s3:esp32s3:esp32s3
          sketch-paths: |
            ./Done.ino
          libraries: |
            ESP32s3Servo
            MPU6050
            TinyGPSPlus
            Adafruit BMP280 Library
            Adafruit HMC5883 Unified
            Adafruit Unified Sensor
          platforms: |
            - name: esp32s3:esp32s3
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32s3/gh-pages/package_esp32s3_index.json
